# Site settings
title: kuan-ying chou's website
email: kuanyingchou@gmail.com
baseurl: ""
url: "http://kuanyingchou.github.io"
twitter_username: kuanyingchou
github_username:  kuanyingchou

# Build settings
markdown: kramdown
permalink: pretty

# name: "kuan-ying chou's website"
author: "Kuan-Ying Chou"
paginate: 5
